#пример запроса на логин
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "testUsername2",
  "password": "12345"
}

###

GET http://localhost:8080/user/info?id=20ffb2dc-8b4b-11eb-a995-b3373ebc289e
Content-Type: application/json

###

GET http://localhost:8080/table?id=4e938f2a-9145-11eb-b903-97e42ad2b3c4
Content-Type: application/json

###

GET http://localhost:8080/template
Content-Type: application/json

###

PUT http://localhost:8080/template
Content-Type: application/json

{
  "name": "template",
  "organization": "all",
  "creationDate": "2021-03-31T14:14:04.015+00:00",
  "modifiedDate": "2021-03-31T14:14:04.015+00:00",
  "folderStructure": [
    {
      "name": "element1",
      "children": [
        {
          "name": "element1.1",
          "children": [
            {
              "name": "element1.1.1",
              "children": null,
              "creationDate": "2021-03-31T14:21:37.430+00:00",
              "modifiedDate": "2021-03-31T14:21:37.430+00:00"
            }
          ],
          "creationDate": "2021-03-31T14:21:37.430+00:00",
          "modifiedDate": "2021-03-31T14:21:37.430+00:00"
        },
        {
          "name": "element1.2",
          "children": null,
          "creationDate": "2021-03-31T14:21:37.430+00:00",
          "modifiedDate": "2021-03-31T14:21:37.430+00:00"
        }
      ],
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    },
    {
      "name": "element2",
      "children": null,
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    },
    {
      "name": "element3",
      "children": null,
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    },
    {
      "name": "element4",
      "children": null,
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    },
    {
      "name": "element5",
      "children": null,
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    }
  ]
}

###
DELETE http://localhost:8080/template
Content-Type: application/json

###
POST http://localhost:8080/template
Content-Type: application/json

{
  "name": "template",
  "organization": "all",
  "creationDate": "2021-03-31T14:14:04.015+00:00",
  "modifiedDate": "2021-03-31T14:14:04.015+00:00",
  "folderStructure": [
    {
      "name": "element1",
      "children": [
        {
          "name": "element1.1",
          "children": [
            {
              "name": "element1.1.1",
              "children": null,
              "creationDate": "2021-03-31T14:21:37.430+00:00",
              "modifiedDate": "2021-03-31T14:21:37.430+00:00"
            }
          ],
          "creationDate": "2021-03-31T14:21:37.430+00:00",
          "modifiedDate": "2021-03-31T14:21:37.430+00:00"
        },
        {
          "name": "element1.2",
          "children": null,
          "creationDate": "2021-03-31T14:21:37.430+00:00",
          "modifiedDate": "2021-03-31T14:21:37.430+00:00"
        }
      ],
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    },
    {
      "name": "element2",
      "children": null,
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    },
    {
      "name": "element3",
      "children": null,
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    },
    {
      "name": "element4",
      "children": null,
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    },
    {
      "name": "element5",
      "children": null,
      "creationDate": "2021-03-31T14:21:37.430+00:00",
      "modifiedDate": "2021-03-31T14:21:37.430+00:00"
    }
  ]
}
